import { Context, Next } from 'hono'
import { jwtVerify } from 'jose'

export type AuthUser = {
  id: string
  role: 'super_admin' | 'dept_admin' | 'content_editor' | 'viewer'
  department: string | null
}

export async function authMiddleware(c: Context, next: Next) {
  const authHeader = c.req.header('Authorization')
  
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return c.json({ error: 'Unauthorized: Missing or invalid Authorization header' }, 401)
  }

  const token = authHeader.split(' ')[1]
  
  try {
    // NextAuth/Auth.js often uses HKDF for derived keys, but for standard JWTs
    // generated by our app, we expect the raw JWT_SECRET to be used as a Uint8Array.
    const secret = new TextEncoder().encode(c.env.JWT_SECRET)
    
    // Note: If NextAuth's default JWE is passed, this will fail. We assume the client 
    // will pass a standard JWT signed with HS256 for API access.
    const { payload } = await jwtVerify(token, secret)
    
    c.set('user', {
      id: payload.sub as string,
      role: payload.role as string,
      department: payload.department as string | null,
    })
    
    await next()
  } catch (error) {
    return c.json({ error: 'Unauthorized: Invalid token' }, 401)
  }
}

export function requireRole(allowedRoles: AuthUser['role'][]) {
  return async (c: Context, next: Next) => {
    const user = c.get('user') as AuthUser | undefined
    if (!user) {
      return c.json({ error: 'Unauthorized' }, 401)
    }
    
    if (!allowedRoles.includes(user.role)) {
      return c.json({ error: 'Forbidden: Insufficient permissions' }, 403)
    }
    
    await next()
  }
}
